export interface Facility {
    _id: string;
    name: string;
    email: string;
    contactPhoneNo: string;
    contactFullName: string;
    checkValidation: string;
    departments: [any];
    minorLocations: [any];
    facilityTypeId: string;
    facilityClassId: string;
    address: any;
    addressObj: any;
    verificationToken: string;
    website: string;
    shortName: string;
    password?: string;
    facilityItem?: any;
    countryItem?: any;
    wardId?: string;
    logo: string;
    isTokenVerified: boolean;
    facilitymoduleId: [any];
    logoObject: any;
    description: string;
    facilityClassItem: any;
    facilityOwnershipId: any;
    facilityModules: any;
    invitees: any;
    country?:any;
    wallet:any;
    primaryContactPhoneNo?: any;
}
